/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Ability
 */
export interface Ability {
    /**
     * 
     * @type {number}
     * @memberof Ability
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Ability
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof Ability
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Ability
     */
    name_zh: string;
    /**
     * 
     * @type {string}
     * @memberof Ability
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Ability
     */
    description_zh?: string;
    /**
     * 
     * @type {string}
     * @memberof Ability
     */
    tag?: string;
    /**
     * 
     * @type {Date}
     * @memberof Ability
     */
    createTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof Ability
     */
    updateTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Ability
     */
    deleteAt?: Date;
}

/**
 * Check if a given object implements the Ability interface.
 */
export function instanceOfAbility(value: object): value is Ability {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('name_zh' in value) || value['name_zh'] === undefined) return false;
    if (!('createTime' in value) || value['createTime'] === undefined) return false;
    return true;
}

export function AbilityFromJSON(json: any): Ability {
    return AbilityFromJSONTyped(json, false);
}

export function AbilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ability {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'code': json['code'],
        'name': json['name'],
        'name_zh': json['name_zh'],
        'description': json['description'] == null ? undefined : json['description'],
        'description_zh': json['description_zh'] == null ? undefined : json['description_zh'],
        'tag': json['tag'] == null ? undefined : json['tag'],
        'createTime': (new Date(json['createTime'])),
        'updateTime': json['updateTime'] == null ? undefined : (new Date(json['updateTime'])),
        'deleteAt': json['deleteAt'] == null ? undefined : (new Date(json['deleteAt'])),
    };
}

export function AbilityToJSON(json: any): Ability {
    return AbilityToJSONTyped(json, false);
}

export function AbilityToJSONTyped(value?: Ability | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'name': value['name'],
        'name_zh': value['name_zh'],
        'description': value['description'],
        'description_zh': value['description_zh'],
        'tag': value['tag'],
        'createTime': value['createTime'].toISOString(),
        'updateTime': value['updateTime'] == null ? value['updateTime'] : value['updateTime'].toISOString(),
        'deleteAt': value['deleteAt'] == null ? value['deleteAt'] : value['deleteAt'].toISOString(),
    };
}

