/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BonusWithdrawRequestDTO
 */
export interface BonusWithdrawRequestDTO {
    /**
     * 
     * @type {number}
     * @memberof BonusWithdrawRequestDTO
     */
    bonus: number;
    /**
     * 
     * @type {string}
     * @memberof BonusWithdrawRequestDTO
     */
    reason?: string;
}

/**
 * Check if a given object implements the BonusWithdrawRequestDTO interface.
 */
export function instanceOfBonusWithdrawRequestDTO(value: object): value is BonusWithdrawRequestDTO {
    if (!('bonus' in value) || value['bonus'] === undefined) return false;
    return true;
}

export function BonusWithdrawRequestDTOFromJSON(json: any): BonusWithdrawRequestDTO {
    return BonusWithdrawRequestDTOFromJSONTyped(json, false);
}

export function BonusWithdrawRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BonusWithdrawRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'bonus': json['bonus'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function BonusWithdrawRequestDTOToJSON(json: any): BonusWithdrawRequestDTO {
    return BonusWithdrawRequestDTOToJSONTyped(json, false);
}

export function BonusWithdrawRequestDTOToJSONTyped(value?: BonusWithdrawRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bonus': value['bonus'],
        'reason': value['reason'],
    };
}

