/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckAbilityRequestDTO
 */
export interface CheckAbilityRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof CheckAbilityRequestDTO
     */
    ability: string;
}

/**
 * Check if a given object implements the CheckAbilityRequestDTO interface.
 */
export function instanceOfCheckAbilityRequestDTO(value: object): value is CheckAbilityRequestDTO {
    if (!('ability' in value) || value['ability'] === undefined) return false;
    return true;
}

export function CheckAbilityRequestDTOFromJSON(json: any): CheckAbilityRequestDTO {
    return CheckAbilityRequestDTOFromJSONTyped(json, false);
}

export function CheckAbilityRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckAbilityRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'ability': json['ability'],
    };
}

export function CheckAbilityRequestDTOToJSON(json: any): CheckAbilityRequestDTO {
    return CheckAbilityRequestDTOToJSONTyped(json, false);
}

export function CheckAbilityRequestDTOToJSONTyped(value?: CheckAbilityRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ability': value['ability'],
    };
}

