/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmSubscriptionResponseDTO
 */
export interface ConfirmSubscriptionResponseDTO {
    /**
     * 
     * @type {string}
     * @memberof ConfirmSubscriptionResponseDTO
     */
    subscription_no: string;
    /**
     * 
     * @type {string}
     * @memberof ConfirmSubscriptionResponseDTO
     */
    out_trade_no: string;
    /**
     * 
     * @type {string}
     * @memberof ConfirmSubscriptionResponseDTO
     */
    subscription_status: ConfirmSubscriptionResponseDTOSubscriptionStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof ConfirmSubscriptionResponseDTO
     */
    order_status: number;
    /**
     * 
     * @type {boolean}
     * @memberof ConfirmSubscriptionResponseDTO
     */
    active?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ConfirmSubscriptionResponseDTO
     */
    expires_at?: number;
}


/**
 * @export
 */
export const ConfirmSubscriptionResponseDTOSubscriptionStatusEnum = {
    Pending: 'PENDING',
    Active: 'ACTIVE',
    GracePeriod: 'GRACE_PERIOD',
    BillingRetry: 'BILLING_RETRY',
    Expired: 'EXPIRED',
    Cancelled: 'CANCELLED',
    Revoked: 'REVOKED',
    Refunded: 'REFUNDED'
} as const;
export type ConfirmSubscriptionResponseDTOSubscriptionStatusEnum = typeof ConfirmSubscriptionResponseDTOSubscriptionStatusEnum[keyof typeof ConfirmSubscriptionResponseDTOSubscriptionStatusEnum];


/**
 * Check if a given object implements the ConfirmSubscriptionResponseDTO interface.
 */
export function instanceOfConfirmSubscriptionResponseDTO(value: object): value is ConfirmSubscriptionResponseDTO {
    if (!('subscription_no' in value) || value['subscription_no'] === undefined) return false;
    if (!('out_trade_no' in value) || value['out_trade_no'] === undefined) return false;
    if (!('subscription_status' in value) || value['subscription_status'] === undefined) return false;
    if (!('order_status' in value) || value['order_status'] === undefined) return false;
    return true;
}

export function ConfirmSubscriptionResponseDTOFromJSON(json: any): ConfirmSubscriptionResponseDTO {
    return ConfirmSubscriptionResponseDTOFromJSONTyped(json, false);
}

export function ConfirmSubscriptionResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmSubscriptionResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'subscription_no': json['subscription_no'],
        'out_trade_no': json['out_trade_no'],
        'subscription_status': json['subscription_status'],
        'order_status': json['order_status'],
        'active': json['active'] == null ? undefined : json['active'],
        'expires_at': json['expires_at'] == null ? undefined : json['expires_at'],
    };
}

export function ConfirmSubscriptionResponseDTOToJSON(json: any): ConfirmSubscriptionResponseDTO {
    return ConfirmSubscriptionResponseDTOToJSONTyped(json, false);
}

export function ConfirmSubscriptionResponseDTOToJSONTyped(value?: ConfirmSubscriptionResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscription_no': value['subscription_no'],
        'out_trade_no': value['out_trade_no'],
        'subscription_status': value['subscription_status'],
        'order_status': value['order_status'],
        'active': value['active'],
        'expires_at': value['expires_at'],
    };
}

