/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmAppleSubscriptionRequestDTO
 */
export interface ConfirmAppleSubscriptionRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof ConfirmAppleSubscriptionRequestDTO
     */
    original_transaction_id: string;
}

/**
 * Check if a given object implements the ConfirmAppleSubscriptionRequestDTO interface.
 */
export function instanceOfConfirmAppleSubscriptionRequestDTO(value: object): value is ConfirmAppleSubscriptionRequestDTO {
    if (!('original_transaction_id' in value) || value['original_transaction_id'] === undefined) return false;
    return true;
}

export function ConfirmAppleSubscriptionRequestDTOFromJSON(json: any): ConfirmAppleSubscriptionRequestDTO {
    return ConfirmAppleSubscriptionRequestDTOFromJSONTyped(json, false);
}

export function ConfirmAppleSubscriptionRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmAppleSubscriptionRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'original_transaction_id': json['original_transaction_id'],
    };
}

export function ConfirmAppleSubscriptionRequestDTOToJSON(json: any): ConfirmAppleSubscriptionRequestDTO {
    return ConfirmAppleSubscriptionRequestDTOToJSONTyped(json, false);
}

export function ConfirmAppleSubscriptionRequestDTOToJSONTyped(value?: ConfirmAppleSubscriptionRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'original_transaction_id': value['original_transaction_id'],
    };
}

