/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetOrderDetailRequestDTO
 */
export interface GetOrderDetailRequestDTO {
    /**
     * 
     * @type {number}
     * @memberof GetOrderDetailRequestDTO
     */
    order_id: number;
}

/**
 * Check if a given object implements the GetOrderDetailRequestDTO interface.
 */
export function instanceOfGetOrderDetailRequestDTO(value: object): value is GetOrderDetailRequestDTO {
    if (!('order_id' in value) || value['order_id'] === undefined) return false;
    return true;
}

export function GetOrderDetailRequestDTOFromJSON(json: any): GetOrderDetailRequestDTO {
    return GetOrderDetailRequestDTOFromJSONTyped(json, false);
}

export function GetOrderDetailRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrderDetailRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'order_id': json['order_id'],
    };
}

export function GetOrderDetailRequestDTOToJSON(json: any): GetOrderDetailRequestDTO {
    return GetOrderDetailRequestDTOToJSONTyped(json, false);
}

export function GetOrderDetailRequestDTOToJSONTyped(value?: GetOrderDetailRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'order_id': value['order_id'],
    };
}

