/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductResponseDTO } from './ProductResponseDTO';
import {
    ProductResponseDTOFromJSON,
    ProductResponseDTOFromJSONTyped,
    ProductResponseDTOToJSON,
    ProductResponseDTOToJSONTyped,
} from './ProductResponseDTO';

/**
 * 
 * @export
 * @interface GetOrderDetailResponseDTO
 */
export interface GetOrderDetailResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof GetOrderDetailResponseDTO
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof GetOrderDetailResponseDTO
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof GetOrderDetailResponseDTO
     */
    status: number;
    /**
     * 
     * @type {ProductResponseDTO}
     * @memberof GetOrderDetailResponseDTO
     */
    product: ProductResponseDTO;
}

/**
 * Check if a given object implements the GetOrderDetailResponseDTO interface.
 */
export function instanceOfGetOrderDetailResponseDTO(value: object): value is GetOrderDetailResponseDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('product' in value) || value['product'] === undefined) return false;
    return true;
}

export function GetOrderDetailResponseDTOFromJSON(json: any): GetOrderDetailResponseDTO {
    return GetOrderDetailResponseDTOFromJSONTyped(json, false);
}

export function GetOrderDetailResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrderDetailResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'price': json['price'],
        'status': json['status'],
        'product': ProductResponseDTOFromJSON(json['product']),
    };
}

export function GetOrderDetailResponseDTOToJSON(json: any): GetOrderDetailResponseDTO {
    return GetOrderDetailResponseDTOToJSONTyped(json, false);
}

export function GetOrderDetailResponseDTOToJSONTyped(value?: GetOrderDetailResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'price': value['price'],
        'status': value['status'],
        'product': ProductResponseDTOToJSON(value['product']),
    };
}

