/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetOrderDetailByPaypalOrderRequestDTO
 */
export interface GetOrderDetailByPaypalOrderRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof GetOrderDetailByPaypalOrderRequestDTO
     */
    paypal_order_id: string;
}

/**
 * Check if a given object implements the GetOrderDetailByPaypalOrderRequestDTO interface.
 */
export function instanceOfGetOrderDetailByPaypalOrderRequestDTO(value: object): value is GetOrderDetailByPaypalOrderRequestDTO {
    if (!('paypal_order_id' in value) || value['paypal_order_id'] === undefined) return false;
    return true;
}

export function GetOrderDetailByPaypalOrderRequestDTOFromJSON(json: any): GetOrderDetailByPaypalOrderRequestDTO {
    return GetOrderDetailByPaypalOrderRequestDTOFromJSONTyped(json, false);
}

export function GetOrderDetailByPaypalOrderRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrderDetailByPaypalOrderRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'paypal_order_id': json['paypal_order_id'],
    };
}

export function GetOrderDetailByPaypalOrderRequestDTOToJSON(json: any): GetOrderDetailByPaypalOrderRequestDTO {
    return GetOrderDetailByPaypalOrderRequestDTOToJSONTyped(json, false);
}

export function GetOrderDetailByPaypalOrderRequestDTOToJSONTyped(value?: GetOrderDetailByPaypalOrderRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paypal_order_id': value['paypal_order_id'],
    };
}

