/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetProductAbilitiesRequestDTO
 */
export interface GetProductAbilitiesRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof GetProductAbilitiesRequestDTO
     */
    product_uuid: string;
}

/**
 * Check if a given object implements the GetProductAbilitiesRequestDTO interface.
 */
export function instanceOfGetProductAbilitiesRequestDTO(value: object): value is GetProductAbilitiesRequestDTO {
    if (!('product_uuid' in value) || value['product_uuid'] === undefined) return false;
    return true;
}

export function GetProductAbilitiesRequestDTOFromJSON(json: any): GetProductAbilitiesRequestDTO {
    return GetProductAbilitiesRequestDTOFromJSONTyped(json, false);
}

export function GetProductAbilitiesRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProductAbilitiesRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'product_uuid': json['product_uuid'],
    };
}

export function GetProductAbilitiesRequestDTOToJSON(json: any): GetProductAbilitiesRequestDTO {
    return GetProductAbilitiesRequestDTOToJSONTyped(json, false);
}

export function GetProductAbilitiesRequestDTOToJSONTyped(value?: GetProductAbilitiesRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'product_uuid': value['product_uuid'],
    };
}

