/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Ability } from './Ability';
import {
    AbilityFromJSON,
    AbilityFromJSONTyped,
    AbilityToJSON,
    AbilityToJSONTyped,
} from './Ability';

/**
 * 
 * @export
 * @interface GetProductAbilitiesResponseDTO
 */
export interface GetProductAbilitiesResponseDTO {
    /**
     * 
     * @type {Array<Ability>}
     * @memberof GetProductAbilitiesResponseDTO
     */
    abilities: Array<Ability>;
}

/**
 * Check if a given object implements the GetProductAbilitiesResponseDTO interface.
 */
export function instanceOfGetProductAbilitiesResponseDTO(value: object): value is GetProductAbilitiesResponseDTO {
    if (!('abilities' in value) || value['abilities'] === undefined) return false;
    return true;
}

export function GetProductAbilitiesResponseDTOFromJSON(json: any): GetProductAbilitiesResponseDTO {
    return GetProductAbilitiesResponseDTOFromJSONTyped(json, false);
}

export function GetProductAbilitiesResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProductAbilitiesResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'abilities': ((json['abilities'] as Array<any>).map(AbilityFromJSON)),
    };
}

export function GetProductAbilitiesResponseDTOToJSON(json: any): GetProductAbilitiesResponseDTO {
    return GetProductAbilitiesResponseDTOToJSONTyped(json, false);
}

export function GetProductAbilitiesResponseDTOToJSONTyped(value?: GetProductAbilitiesResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'abilities': ((value['abilities'] as Array<any>).map(AbilityToJSON)),
    };
}

