/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetProductRequestByUUIDDTO
 */
export interface GetProductRequestByUUIDDTO {
    /**
     * 
     * @type {string}
     * @memberof GetProductRequestByUUIDDTO
     */
    product_uuid: string;
}

/**
 * Check if a given object implements the GetProductRequestByUUIDDTO interface.
 */
export function instanceOfGetProductRequestByUUIDDTO(value: object): value is GetProductRequestByUUIDDTO {
    if (!('product_uuid' in value) || value['product_uuid'] === undefined) return false;
    return true;
}

export function GetProductRequestByUUIDDTOFromJSON(json: any): GetProductRequestByUUIDDTO {
    return GetProductRequestByUUIDDTOFromJSONTyped(json, false);
}

export function GetProductRequestByUUIDDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProductRequestByUUIDDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'product_uuid': json['product_uuid'],
    };
}

export function GetProductRequestByUUIDDTOToJSON(json: any): GetProductRequestByUUIDDTO {
    return GetProductRequestByUUIDDTOToJSONTyped(json, false);
}

export function GetProductRequestByUUIDDTOToJSONTyped(value?: GetProductRequestByUUIDDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'product_uuid': value['product_uuid'],
    };
}

