/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetProductResponseDTO
 */
export interface GetProductResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof GetProductResponseDTO
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof GetProductResponseDTO
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof GetProductResponseDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetProductResponseDTO
     */
    name_zh: string;
    /**
     * 
     * @type {string}
     * @memberof GetProductResponseDTO
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof GetProductResponseDTO
     */
    description_zh: string;
    /**
     * 
     * @type {number}
     * @memberof GetProductResponseDTO
     */
    price: number;
}

/**
 * Check if a given object implements the GetProductResponseDTO interface.
 */
export function instanceOfGetProductResponseDTO(value: object): value is GetProductResponseDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('name_zh' in value) || value['name_zh'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('description_zh' in value) || value['description_zh'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function GetProductResponseDTOFromJSON(json: any): GetProductResponseDTO {
    return GetProductResponseDTOFromJSONTyped(json, false);
}

export function GetProductResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProductResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'uuid': json['uuid'],
        'name': json['name'],
        'name_zh': json['name_zh'],
        'description': json['description'],
        'description_zh': json['description_zh'],
        'price': json['price'],
    };
}

export function GetProductResponseDTOToJSON(json: any): GetProductResponseDTO {
    return GetProductResponseDTOToJSONTyped(json, false);
}

export function GetProductResponseDTOToJSONTyped(value?: GetProductResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'uuid': value['uuid'],
        'name': value['name'],
        'name_zh': value['name_zh'],
        'description': value['description'],
        'description_zh': value['description_zh'],
        'price': value['price'],
    };
}

