/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NormalResponseDTO
 */
export interface NormalResponseDTO {
    /**
     * 
     * @type {string}
     * @memberof NormalResponseDTO
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof NormalResponseDTO
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof NormalResponseDTO
     */
    code: number;
}

/**
 * Check if a given object implements the NormalResponseDTO interface.
 */
export function instanceOfNormalResponseDTO(value: object): value is NormalResponseDTO {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function NormalResponseDTOFromJSON(json: any): NormalResponseDTO {
    return NormalResponseDTOFromJSONTyped(json, false);
}

export function NormalResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): NormalResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'],
        'code': json['code'],
    };
}

export function NormalResponseDTOToJSON(json: any): NormalResponseDTO {
    return NormalResponseDTOToJSONTyped(json, false);
}

export function NormalResponseDTOToJSONTyped(value?: NormalResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'success': value['success'],
        'code': value['code'],
    };
}

