/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderStatusResponseDTO
 */
export interface OrderStatusResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof OrderStatusResponseDTO
     */
    status: number;
}

/**
 * Check if a given object implements the OrderStatusResponseDTO interface.
 */
export function instanceOfOrderStatusResponseDTO(value: object): value is OrderStatusResponseDTO {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function OrderStatusResponseDTOFromJSON(json: any): OrderStatusResponseDTO {
    return OrderStatusResponseDTOFromJSONTyped(json, false);
}

export function OrderStatusResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderStatusResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function OrderStatusResponseDTOToJSON(json: any): OrderStatusResponseDTO {
    return OrderStatusResponseDTOToJSONTyped(json, false);
}

export function OrderStatusResponseDTOToJSONTyped(value?: OrderStatusResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

