/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderStatusRequestDTO
 */
export interface OrderStatusRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof OrderStatusRequestDTO
     */
    order_no: string;
}

/**
 * Check if a given object implements the OrderStatusRequestDTO interface.
 */
export function instanceOfOrderStatusRequestDTO(value: object): value is OrderStatusRequestDTO {
    if (!('order_no' in value) || value['order_no'] === undefined) return false;
    return true;
}

export function OrderStatusRequestDTOFromJSON(json: any): OrderStatusRequestDTO {
    return OrderStatusRequestDTOFromJSONTyped(json, false);
}

export function OrderStatusRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderStatusRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'order_no': json['order_no'],
    };
}

export function OrderStatusRequestDTOToJSON(json: any): OrderStatusRequestDTO {
    return OrderStatusRequestDTOToJSONTyped(json, false);
}

export function OrderStatusRequestDTOToJSONTyped(value?: OrderStatusRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'order_no': value['order_no'],
    };
}

