/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';

/**
 * 
 * @export
 * @interface Plan
 */
export interface Plan {
    /**
     * 
     * @type {number}
     * @memberof Plan
     */
    id?: number;
    /**
     * 
     * @type {Product}
     * @memberof Plan
     */
    product?: Product;
    /**
     * 
     * @type {number}
     * @memberof Plan
     */
    expiresIn?: number;
    /**
     * 
     * @type {Date}
     * @memberof Plan
     */
    createTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof Plan
     */
    updateTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Plan
     */
    deleteAt?: Date;
}

/**
 * Check if a given object implements the Plan interface.
 */
export function instanceOfPlan(value: object): value is Plan {
    if (!('createTime' in value) || value['createTime'] === undefined) return false;
    return true;
}

export function PlanFromJSON(json: any): Plan {
    return PlanFromJSONTyped(json, false);
}

export function PlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): Plan {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'product': json['product'] == null ? undefined : ProductFromJSON(json['product']),
        'expiresIn': json['expiresIn'] == null ? undefined : json['expiresIn'],
        'createTime': (new Date(json['createTime'])),
        'updateTime': json['updateTime'] == null ? undefined : (new Date(json['updateTime'])),
        'deleteAt': json['deleteAt'] == null ? undefined : (new Date(json['deleteAt'])),
    };
}

export function PlanToJSON(json: any): Plan {
    return PlanToJSONTyped(json, false);
}

export function PlanToJSONTyped(value?: Plan | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'product': ProductToJSON(value['product']),
        'expiresIn': value['expiresIn'],
        'createTime': value['createTime'].toISOString(),
        'updateTime': value['updateTime'] == null ? value['updateTime'] : value['updateTime'].toISOString(),
        'deleteAt': value['deleteAt'] == null ? value['deleteAt'] : value['deleteAt'].toISOString(),
    };
}

