/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrePayProductResponseDTO
 */
export interface PrePayProductResponseDTO {
    /**
     * 
     * @type {string}
     * @memberof PrePayProductResponseDTO
     */
    out_trade_no: string;
    /**
     * 
     * @type {string}
     * @memberof PrePayProductResponseDTO
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof PrePayProductResponseDTO
     */
    product_name: string;
    /**
     * 
     * @type {string}
     * @memberof PrePayProductResponseDTO
     */
    product_name_zh: string;
    /**
     * 
     * @type {number}
     * @memberof PrePayProductResponseDTO
     */
    price: number;
}

/**
 * Check if a given object implements the PrePayProductResponseDTO interface.
 */
export function instanceOfPrePayProductResponseDTO(value: object): value is PrePayProductResponseDTO {
    if (!('out_trade_no' in value) || value['out_trade_no'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('product_name' in value) || value['product_name'] === undefined) return false;
    if (!('product_name_zh' in value) || value['product_name_zh'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function PrePayProductResponseDTOFromJSON(json: any): PrePayProductResponseDTO {
    return PrePayProductResponseDTOFromJSONTyped(json, false);
}

export function PrePayProductResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrePayProductResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'out_trade_no': json['out_trade_no'],
        'code': json['code'],
        'product_name': json['product_name'],
        'product_name_zh': json['product_name_zh'],
        'price': json['price'],
    };
}

export function PrePayProductResponseDTOToJSON(json: any): PrePayProductResponseDTO {
    return PrePayProductResponseDTOToJSONTyped(json, false);
}

export function PrePayProductResponseDTOToJSONTyped(value?: PrePayProductResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'out_trade_no': value['out_trade_no'],
        'code': value['code'],
        'product_name': value['product_name'],
        'product_name_zh': value['product_name_zh'],
        'price': value['price'],
    };
}

