/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrePaySubscriptionRequestDTO
 */
export interface PrePaySubscriptionRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof PrePaySubscriptionRequestDTO
     */
    product_uuid: string;
    /**
     * 
     * @type {string}
     * @memberof PrePaySubscriptionRequestDTO
     */
    pay_way: PrePaySubscriptionRequestDTOPayWayEnum;
    /**
     * 
     * @type {string}
     * @memberof PrePaySubscriptionRequestDTO
     */
    category: PrePaySubscriptionRequestDTOCategoryEnum;
    /**
     * 
     * @type {string}
     * @memberof PrePaySubscriptionRequestDTO
     */
    currency_code: PrePaySubscriptionRequestDTOCurrencyCodeEnum;
}


/**
 * @export
 */
export const PrePaySubscriptionRequestDTOPayWayEnum = {
    Wechat: 'WECHAT',
    Alipay: 'ALIPAY',
    Paypal: 'PAYPAL',
    ApplePay: 'APPLE_PAY'
} as const;
export type PrePaySubscriptionRequestDTOPayWayEnum = typeof PrePaySubscriptionRequestDTOPayWayEnum[keyof typeof PrePaySubscriptionRequestDTOPayWayEnum];

/**
 * @export
 */
export const PrePaySubscriptionRequestDTOCategoryEnum = {
    UserPlan: 'USER_PLAN',
    Section: 'SECTION'
} as const;
export type PrePaySubscriptionRequestDTOCategoryEnum = typeof PrePaySubscriptionRequestDTOCategoryEnum[keyof typeof PrePaySubscriptionRequestDTOCategoryEnum];

/**
 * @export
 */
export const PrePaySubscriptionRequestDTOCurrencyCodeEnum = {
    Cny: 'CNY',
    Usd: 'USD',
    Eur: 'EUR',
    Hkd: 'HKD',
    Jpy: 'JPY'
} as const;
export type PrePaySubscriptionRequestDTOCurrencyCodeEnum = typeof PrePaySubscriptionRequestDTOCurrencyCodeEnum[keyof typeof PrePaySubscriptionRequestDTOCurrencyCodeEnum];


/**
 * Check if a given object implements the PrePaySubscriptionRequestDTO interface.
 */
export function instanceOfPrePaySubscriptionRequestDTO(value: object): value is PrePaySubscriptionRequestDTO {
    if (!('product_uuid' in value) || value['product_uuid'] === undefined) return false;
    if (!('pay_way' in value) || value['pay_way'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('currency_code' in value) || value['currency_code'] === undefined) return false;
    return true;
}

export function PrePaySubscriptionRequestDTOFromJSON(json: any): PrePaySubscriptionRequestDTO {
    return PrePaySubscriptionRequestDTOFromJSONTyped(json, false);
}

export function PrePaySubscriptionRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrePaySubscriptionRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'product_uuid': json['product_uuid'],
        'pay_way': json['pay_way'],
        'category': json['category'],
        'currency_code': json['currency_code'],
    };
}

export function PrePaySubscriptionRequestDTOToJSON(json: any): PrePaySubscriptionRequestDTO {
    return PrePaySubscriptionRequestDTOToJSONTyped(json, false);
}

export function PrePaySubscriptionRequestDTOToJSONTyped(value?: PrePaySubscriptionRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'product_uuid': value['product_uuid'],
        'pay_way': value['pay_way'],
        'category': value['category'],
        'currency_code': value['currency_code'],
    };
}

