/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrePayProductRequestDTO
 */
export interface PrePayProductRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof PrePayProductRequestDTO
     */
    product_uuid: string;
    /**
     * 
     * @type {number}
     * @memberof PrePayProductRequestDTO
     */
    pay_way: number;
    /**
     * 
     * @type {string}
     * @memberof PrePayProductRequestDTO
     */
    category: string;
}

/**
 * Check if a given object implements the PrePayProductRequestDTO interface.
 */
export function instanceOfPrePayProductRequestDTO(value: object): value is PrePayProductRequestDTO {
    if (!('product_uuid' in value) || value['product_uuid'] === undefined) return false;
    if (!('pay_way' in value) || value['pay_way'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    return true;
}

export function PrePayProductRequestDTOFromJSON(json: any): PrePayProductRequestDTO {
    return PrePayProductRequestDTOFromJSONTyped(json, false);
}

export function PrePayProductRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrePayProductRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'product_uuid': json['product_uuid'],
        'pay_way': json['pay_way'],
        'category': json['category'],
    };
}

export function PrePayProductRequestDTOToJSON(json: any): PrePayProductRequestDTO {
    return PrePayProductRequestDTOToJSONTyped(json, false);
}

export function PrePayProductRequestDTOToJSONTyped(value?: PrePayProductRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'product_uuid': value['product_uuid'],
        'pay_way': value['pay_way'],
        'category': value['category'],
    };
}

