/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrePayProductRequestDTO
 */
export interface PrePayProductRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof PrePayProductRequestDTO
     */
    product_uuid: string;
    /**
     * 
     * @type {string}
     * @memberof PrePayProductRequestDTO
     */
    pay_way: PrePayProductRequestDTOPayWayEnum;
    /**
     * 
     * @type {string}
     * @memberof PrePayProductRequestDTO
     */
    category: PrePayProductRequestDTOCategoryEnum;
    /**
     * 
     * @type {string}
     * @memberof PrePayProductRequestDTO
     */
    currency_code: PrePayProductRequestDTOCurrencyCodeEnum;
}


/**
 * @export
 */
export const PrePayProductRequestDTOPayWayEnum = {
    Wechat: 'WECHAT',
    Alipay: 'ALIPAY',
    Paypal: 'PAYPAL',
    ApplePay: 'APPLE_PAY'
} as const;
export type PrePayProductRequestDTOPayWayEnum = typeof PrePayProductRequestDTOPayWayEnum[keyof typeof PrePayProductRequestDTOPayWayEnum];

/**
 * @export
 */
export const PrePayProductRequestDTOCategoryEnum = {
    UserPlan: 'USER_PLAN',
    Section: 'SECTION'
} as const;
export type PrePayProductRequestDTOCategoryEnum = typeof PrePayProductRequestDTOCategoryEnum[keyof typeof PrePayProductRequestDTOCategoryEnum];

/**
 * @export
 */
export const PrePayProductRequestDTOCurrencyCodeEnum = {
    Cny: 'CNY',
    Usd: 'USD',
    Eur: 'EUR',
    Hkd: 'HKD',
    Jpy: 'JPY'
} as const;
export type PrePayProductRequestDTOCurrencyCodeEnum = typeof PrePayProductRequestDTOCurrencyCodeEnum[keyof typeof PrePayProductRequestDTOCurrencyCodeEnum];


/**
 * Check if a given object implements the PrePayProductRequestDTO interface.
 */
export function instanceOfPrePayProductRequestDTO(value: object): value is PrePayProductRequestDTO {
    if (!('product_uuid' in value) || value['product_uuid'] === undefined) return false;
    if (!('pay_way' in value) || value['pay_way'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('currency_code' in value) || value['currency_code'] === undefined) return false;
    return true;
}

export function PrePayProductRequestDTOFromJSON(json: any): PrePayProductRequestDTO {
    return PrePayProductRequestDTOFromJSONTyped(json, false);
}

export function PrePayProductRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrePayProductRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'product_uuid': json['product_uuid'],
        'pay_way': json['pay_way'],
        'category': json['category'],
        'currency_code': json['currency_code'],
    };
}

export function PrePayProductRequestDTOToJSON(json: any): PrePayProductRequestDTO {
    return PrePayProductRequestDTOToJSONTyped(json, false);
}

export function PrePayProductRequestDTOToJSONTyped(value?: PrePayProductRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'product_uuid': value['product_uuid'],
        'pay_way': value['pay_way'],
        'category': value['category'],
        'currency_code': value['currency_code'],
    };
}

