/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceItem } from './PriceItem';
import {
    PriceItemFromJSON,
    PriceItemFromJSONTyped,
    PriceItemToJSON,
    PriceItemToJSONTyped,
} from './PriceItem';

/**
 * 
 * @export
 * @interface PrePaySubscriptionResponseDTO
 */
export interface PrePaySubscriptionResponseDTO {
    /**
     * 
     * @type {string}
     * @memberof PrePaySubscriptionResponseDTO
     */
    subscription_no: string;
    /**
     * 
     * @type {string}
     * @memberof PrePaySubscriptionResponseDTO
     */
    out_trade_no: string;
    /**
     * 
     * @type {string}
     * @memberof PrePaySubscriptionResponseDTO
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof PrePaySubscriptionResponseDTO
     */
    product_name: string;
    /**
     * 
     * @type {string}
     * @memberof PrePaySubscriptionResponseDTO
     */
    product_name_zh: string;
    /**
     * 
     * @type {PriceItem}
     * @memberof PrePaySubscriptionResponseDTO
     */
    price: PriceItem;
}

/**
 * Check if a given object implements the PrePaySubscriptionResponseDTO interface.
 */
export function instanceOfPrePaySubscriptionResponseDTO(value: object): value is PrePaySubscriptionResponseDTO {
    if (!('subscription_no' in value) || value['subscription_no'] === undefined) return false;
    if (!('out_trade_no' in value) || value['out_trade_no'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('product_name' in value) || value['product_name'] === undefined) return false;
    if (!('product_name_zh' in value) || value['product_name_zh'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function PrePaySubscriptionResponseDTOFromJSON(json: any): PrePaySubscriptionResponseDTO {
    return PrePaySubscriptionResponseDTOFromJSONTyped(json, false);
}

export function PrePaySubscriptionResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrePaySubscriptionResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'subscription_no': json['subscription_no'],
        'out_trade_no': json['out_trade_no'],
        'code': json['code'],
        'product_name': json['product_name'],
        'product_name_zh': json['product_name_zh'],
        'price': PriceItemFromJSON(json['price']),
    };
}

export function PrePaySubscriptionResponseDTOToJSON(json: any): PrePaySubscriptionResponseDTO {
    return PrePaySubscriptionResponseDTOToJSONTyped(json, false);
}

export function PrePaySubscriptionResponseDTOToJSONTyped(value?: PrePaySubscriptionResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscription_no': value['subscription_no'],
        'out_trade_no': value['out_trade_no'],
        'code': value['code'],
        'product_name': value['product_name'],
        'product_name_zh': value['product_name_zh'],
        'price': PriceItemToJSON(value['price']),
    };
}

