/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PriceItem
 */
export interface PriceItem {
    /**
     * 
     * @type {number}
     * @memberof PriceItem
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof PriceItem
     */
    currency_code: PriceItemCurrencyCodeEnum;
}


/**
 * @export
 */
export const PriceItemCurrencyCodeEnum = {
    Cny: 'CNY',
    Usd: 'USD',
    Eur: 'EUR',
    Hkd: 'HKD',
    Jpy: 'JPY'
} as const;
export type PriceItemCurrencyCodeEnum = typeof PriceItemCurrencyCodeEnum[keyof typeof PriceItemCurrencyCodeEnum];


/**
 * Check if a given object implements the PriceItem interface.
 */
export function instanceOfPriceItem(value: object): value is PriceItem {
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('currency_code' in value) || value['currency_code'] === undefined) return false;
    return true;
}

export function PriceItemFromJSON(json: any): PriceItem {
    return PriceItemFromJSONTyped(json, false);
}

export function PriceItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceItem {
    if (json == null) {
        return json;
    }
    return {
        
        'price': json['price'],
        'currency_code': json['currency_code'],
    };
}

export function PriceItemToJSON(json: any): PriceItem {
    return PriceItemToJSONTyped(json, false);
}

export function PriceItemToJSONTyped(value?: PriceItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'price': value['price'],
        'currency_code': value['currency_code'],
    };
}

