/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    name_zh: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    description_zh: string;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    category: number;
    /**
     * 
     * @type {Date}
     * @memberof Product
     */
    createTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof Product
     */
    updateTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Product
     */
    deleteAt?: Date;
}

/**
 * Check if a given object implements the Product interface.
 */
export function instanceOfProduct(value: object): value is Product {
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('name_zh' in value) || value['name_zh'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('description_zh' in value) || value['description_zh'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('createTime' in value) || value['createTime'] === undefined) return false;
    return true;
}

export function ProductFromJSON(json: any): Product {
    return ProductFromJSONTyped(json, false);
}

export function ProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): Product {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'uuid': json['uuid'],
        'name': json['name'],
        'name_zh': json['name_zh'],
        'description': json['description'],
        'description_zh': json['description_zh'],
        'category': json['category'],
        'createTime': (new Date(json['createTime'])),
        'updateTime': json['updateTime'] == null ? undefined : (new Date(json['updateTime'])),
        'deleteAt': json['deleteAt'] == null ? undefined : (new Date(json['deleteAt'])),
    };
}

export function ProductToJSON(json: any): Product {
    return ProductToJSONTyped(json, false);
}

export function ProductToJSONTyped(value?: Product | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'uuid': value['uuid'],
        'name': value['name'],
        'name_zh': value['name_zh'],
        'description': value['description'],
        'description_zh': value['description_zh'],
        'category': value['category'],
        'createTime': value['createTime'].toISOString(),
        'updateTime': value['updateTime'] == null ? value['updateTime'] : value['updateTime'].toISOString(),
        'deleteAt': value['deleteAt'] == null ? value['deleteAt'] : value['deleteAt'].toISOString(),
    };
}

