/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductResponseDTO
 */
export interface ProductResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof ProductResponseDTO
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseDTO
     */
    name_zh: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseDTO
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseDTO
     */
    description_zh: string;
    /**
     * 
     * @type {number}
     * @memberof ProductResponseDTO
     */
    price: number;
}

/**
 * Check if a given object implements the ProductResponseDTO interface.
 */
export function instanceOfProductResponseDTO(value: object): value is ProductResponseDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('name_zh' in value) || value['name_zh'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('description_zh' in value) || value['description_zh'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    return true;
}

export function ProductResponseDTOFromJSON(json: any): ProductResponseDTO {
    return ProductResponseDTOFromJSONTyped(json, false);
}

export function ProductResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'name_zh': json['name_zh'],
        'description': json['description'],
        'description_zh': json['description_zh'],
        'price': json['price'],
    };
}

export function ProductResponseDTOToJSON(json: any): ProductResponseDTO {
    return ProductResponseDTOToJSONTyped(json, false);
}

export function ProductResponseDTOToJSONTyped(value?: ProductResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'name_zh': value['name_zh'],
        'description': value['description'],
        'description_zh': value['description_zh'],
        'price': value['price'],
    };
}

