/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionStatusResponseDTO
 */
export interface SubscriptionStatusResponseDTO {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionStatusResponseDTO
     */
    subscription_no: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionStatusResponseDTO
     */
    pay_way: SubscriptionStatusResponseDTOPayWayEnum;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionStatusResponseDTO
     */
    status: SubscriptionStatusResponseDTOStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionStatusResponseDTO
     */
    order_status: number;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionStatusResponseDTO
     */
    auto_renew: boolean;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionStatusResponseDTO
     */
    expires_at?: number;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionStatusResponseDTO
     */
    provider_subscription_id?: string;
}


/**
 * @export
 */
export const SubscriptionStatusResponseDTOPayWayEnum = {
    Wechat: 'WECHAT',
    Alipay: 'ALIPAY',
    Paypal: 'PAYPAL',
    ApplePay: 'APPLE_PAY'
} as const;
export type SubscriptionStatusResponseDTOPayWayEnum = typeof SubscriptionStatusResponseDTOPayWayEnum[keyof typeof SubscriptionStatusResponseDTOPayWayEnum];

/**
 * @export
 */
export const SubscriptionStatusResponseDTOStatusEnum = {
    Pending: 'PENDING',
    Active: 'ACTIVE',
    GracePeriod: 'GRACE_PERIOD',
    BillingRetry: 'BILLING_RETRY',
    Expired: 'EXPIRED',
    Cancelled: 'CANCELLED',
    Revoked: 'REVOKED',
    Refunded: 'REFUNDED'
} as const;
export type SubscriptionStatusResponseDTOStatusEnum = typeof SubscriptionStatusResponseDTOStatusEnum[keyof typeof SubscriptionStatusResponseDTOStatusEnum];


/**
 * Check if a given object implements the SubscriptionStatusResponseDTO interface.
 */
export function instanceOfSubscriptionStatusResponseDTO(value: object): value is SubscriptionStatusResponseDTO {
    if (!('subscription_no' in value) || value['subscription_no'] === undefined) return false;
    if (!('pay_way' in value) || value['pay_way'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('order_status' in value) || value['order_status'] === undefined) return false;
    if (!('auto_renew' in value) || value['auto_renew'] === undefined) return false;
    return true;
}

export function SubscriptionStatusResponseDTOFromJSON(json: any): SubscriptionStatusResponseDTO {
    return SubscriptionStatusResponseDTOFromJSONTyped(json, false);
}

export function SubscriptionStatusResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionStatusResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'subscription_no': json['subscription_no'],
        'pay_way': json['pay_way'],
        'status': json['status'],
        'order_status': json['order_status'],
        'auto_renew': json['auto_renew'],
        'expires_at': json['expires_at'] == null ? undefined : json['expires_at'],
        'provider_subscription_id': json['provider_subscription_id'] == null ? undefined : json['provider_subscription_id'],
    };
}

export function SubscriptionStatusResponseDTOToJSON(json: any): SubscriptionStatusResponseDTO {
    return SubscriptionStatusResponseDTOToJSONTyped(json, false);
}

export function SubscriptionStatusResponseDTOToJSONTyped(value?: SubscriptionStatusResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscription_no': value['subscription_no'],
        'pay_way': value['pay_way'],
        'status': value['status'],
        'order_status': value['order_status'],
        'auto_renew': value['auto_renew'],
        'expires_at': value['expires_at'],
        'provider_subscription_id': value['provider_subscription_id'],
    };
}

