/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionStatusRequestDTO
 */
export interface SubscriptionStatusRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionStatusRequestDTO
     */
    subscription_no: string;
}

/**
 * Check if a given object implements the SubscriptionStatusRequestDTO interface.
 */
export function instanceOfSubscriptionStatusRequestDTO(value: object): value is SubscriptionStatusRequestDTO {
    if (!('subscription_no' in value) || value['subscription_no'] === undefined) return false;
    return true;
}

export function SubscriptionStatusRequestDTOFromJSON(json: any): SubscriptionStatusRequestDTO {
    return SubscriptionStatusRequestDTOFromJSONTyped(json, false);
}

export function SubscriptionStatusRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionStatusRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'subscription_no': json['subscription_no'],
    };
}

export function SubscriptionStatusRequestDTOToJSON(json: any): SubscriptionStatusRequestDTO {
    return SubscriptionStatusRequestDTOToJSONTyped(json, false);
}

export function SubscriptionStatusRequestDTOToJSONTyped(value?: SubscriptionStatusRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscription_no': value['subscription_no'],
    };
}

