/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserPlan } from './UserPlan';
import {
    UserPlanFromJSON,
    UserPlanFromJSONTyped,
    UserPlanToJSON,
    UserPlanToJSONTyped,
} from './UserPlan';

/**
 * 
 * @export
 * @interface UserResponseDTO
 */
export interface UserResponseDTO {
    /**
     * 
     * @type {number}
     * @memberof UserResponseDTO
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDTO
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof UserResponseDTO
     */
    nickname: string;
    /**
     * 
     * @type {UserPlan}
     * @memberof UserResponseDTO
     */
    userPlan: UserPlan;
}

/**
 * Check if a given object implements the UserResponseDTO interface.
 */
export function instanceOfUserResponseDTO(value: object): value is UserResponseDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('userPlan' in value) || value['userPlan'] === undefined) return false;
    return true;
}

export function UserResponseDTOFromJSON(json: any): UserResponseDTO {
    return UserResponseDTOFromJSONTyped(json, false);
}

export function UserResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'uuid': json['uuid'],
        'nickname': json['nickname'],
        'userPlan': UserPlanFromJSON(json['userPlan']),
    };
}

export function UserResponseDTOToJSON(json: any): UserResponseDTO {
    return UserResponseDTOToJSONTyped(json, false);
}

export function UserResponseDTOToJSONTyped(value?: UserResponseDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'uuid': value['uuid'],
        'nickname': value['nickname'],
        'userPlan': UserPlanToJSON(value['userPlan']),
    };
}

