/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { Plan } from './Plan';
import {
    PlanFromJSON,
    PlanFromJSONTyped,
    PlanToJSON,
    PlanToJSONTyped,
} from './Plan';

/**
 * 
 * @export
 * @interface UserPlan
 */
export interface UserPlan {
    /**
     * 
     * @type {number}
     * @memberof UserPlan
     */
    id?: number;
    /**
     * 
     * @type {Plan}
     * @memberof UserPlan
     */
    plan?: Plan;
    /**
     * 
     * @type {User}
     * @memberof UserPlan
     */
    user?: User;
    /**
     * 
     * @type {Date}
     * @memberof UserPlan
     */
    startTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserPlan
     */
    expireTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserPlan
     */
    createTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserPlan
     */
    updateTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserPlan
     */
    deleteAt?: Date;
}

/**
 * Check if a given object implements the UserPlan interface.
 */
export function instanceOfUserPlan(value: object): value is UserPlan {
    if (!('startTime' in value) || value['startTime'] === undefined) return false;
    if (!('expireTime' in value) || value['expireTime'] === undefined) return false;
    if (!('createTime' in value) || value['createTime'] === undefined) return false;
    return true;
}

export function UserPlanFromJSON(json: any): UserPlan {
    return UserPlanFromJSONTyped(json, false);
}

export function UserPlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPlan {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'plan': json['plan'] == null ? undefined : PlanFromJSON(json['plan']),
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
        'startTime': (new Date(json['startTime'])),
        'expireTime': (new Date(json['expireTime'])),
        'createTime': (new Date(json['createTime'])),
        'updateTime': json['updateTime'] == null ? undefined : (new Date(json['updateTime'])),
        'deleteAt': json['deleteAt'] == null ? undefined : (new Date(json['deleteAt'])),
    };
}

export function UserPlanToJSON(json: any): UserPlan {
    return UserPlanToJSONTyped(json, false);
}

export function UserPlanToJSONTyped(value?: UserPlan | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'plan': PlanToJSON(value['plan']),
        'user': UserToJSON(value['user']),
        'startTime': value['startTime'].toISOString(),
        'expireTime': value['expireTime'].toISOString(),
        'createTime': value['createTime'].toISOString(),
        'updateTime': value['updateTime'] == null ? value['updateTime'] : value['updateTime'].toISOString(),
        'deleteAt': value['deleteAt'] == null ? value['deleteAt'] : value['deleteAt'].toISOString(),
    };
}

