/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    avatar?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    nickname: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    lastLoginIp?: string;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    lastLoginTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    slogan?: string;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    gender?: number;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    age?: number;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isForbidden?: boolean;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    defaultDocumentReaderModelId?: number;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    defaultRevornixModelId?: number;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    defaultFileDocumentParseUserEngineId?: number;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    defaultWebsiteDocumentParseUserEngineId?: number;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    defaultPodcastUserEngineId?: number;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    defaultReadMarkReason?: number;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    defaultUserFileSystem?: number;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    createTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    updateTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    deleteAt?: Date;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('createTime' in value) || value['createTime'] === undefined) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'uuid': json['uuid'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'nickname': json['nickname'],
        'lastLoginIp': json['lastLoginIp'] == null ? undefined : json['lastLoginIp'],
        'lastLoginTime': json['lastLoginTime'] == null ? undefined : (new Date(json['lastLoginTime'])),
        'slogan': json['slogan'] == null ? undefined : json['slogan'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'age': json['age'] == null ? undefined : json['age'],
        'isForbidden': json['isForbidden'] == null ? undefined : json['isForbidden'],
        'defaultDocumentReaderModelId': json['defaultDocumentReaderModelId'] == null ? undefined : json['defaultDocumentReaderModelId'],
        'defaultRevornixModelId': json['defaultRevornixModelId'] == null ? undefined : json['defaultRevornixModelId'],
        'defaultFileDocumentParseUserEngineId': json['defaultFileDocumentParseUserEngineId'] == null ? undefined : json['defaultFileDocumentParseUserEngineId'],
        'defaultWebsiteDocumentParseUserEngineId': json['defaultWebsiteDocumentParseUserEngineId'] == null ? undefined : json['defaultWebsiteDocumentParseUserEngineId'],
        'defaultPodcastUserEngineId': json['defaultPodcastUserEngineId'] == null ? undefined : json['defaultPodcastUserEngineId'],
        'defaultReadMarkReason': json['defaultReadMarkReason'] == null ? undefined : json['defaultReadMarkReason'],
        'defaultUserFileSystem': json['defaultUserFileSystem'] == null ? undefined : json['defaultUserFileSystem'],
        'createTime': (new Date(json['createTime'])),
        'updateTime': json['updateTime'] == null ? undefined : (new Date(json['updateTime'])),
        'deleteAt': json['deleteAt'] == null ? undefined : (new Date(json['deleteAt'])),
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'uuid': value['uuid'],
        'avatar': value['avatar'],
        'nickname': value['nickname'],
        'lastLoginIp': value['lastLoginIp'],
        'lastLoginTime': value['lastLoginTime'] == null ? value['lastLoginTime'] : value['lastLoginTime'].toISOString(),
        'slogan': value['slogan'],
        'gender': value['gender'],
        'age': value['age'],
        'isForbidden': value['isForbidden'],
        'defaultDocumentReaderModelId': value['defaultDocumentReaderModelId'],
        'defaultRevornixModelId': value['defaultRevornixModelId'],
        'defaultFileDocumentParseUserEngineId': value['defaultFileDocumentParseUserEngineId'],
        'defaultWebsiteDocumentParseUserEngineId': value['defaultWebsiteDocumentParseUserEngineId'],
        'defaultPodcastUserEngineId': value['defaultPodcastUserEngineId'],
        'defaultReadMarkReason': value['defaultReadMarkReason'],
        'defaultUserFileSystem': value['defaultUserFileSystem'],
        'createTime': value['createTime'].toISOString(),
        'updateTime': value['updateTime'] == null ? value['updateTime'] : value['updateTime'].toISOString(),
        'deleteAt': value['deleteAt'] == null ? value['deleteAt'] : value['deleteAt'].toISOString(),
    };
}

