import { API_PREFIX } from "@/config/api"

export default {
    searchUser: API_PREFIX + '/user/search',
    getUserFans: API_PREFIX + '/user/fans',
    getUserFollows: API_PREFIX + '/user/follows',
    createEmailCode: API_PREFIX + '/user/create/email/code',
    createEmailUserVerify: API_PREFIX + '/user/create/email/verify',
    myInfo: API_PREFIX + '/user/mine/info',
    userInfo: API_PREFIX + '/user/info',
    followUser: API_PREFIX + '/user/follow',
    loginUser: API_PREFIX + '/user/login',
    updateToken: API_PREFIX + '/user/token/update',
    updateUserInfo: API_PREFIX + '/user/update',
    updatePassword: API_PREFIX + '/user/password/update',
    updatePasswordEmailCode: API_PREFIX + '/user/password/update/email/code',
    deleteUser: API_PREFIX + '/user/delete',
    bindEmailCode: API_PREFIX + '/user/bind/email/code',
    bindEmailVerify: API_PREFIX + '/user/bind/email/verify',
    unBindEmail: API_PREFIX + '/user/unbind/email',
    initialPassword: API_PREFIX + '/user/password/initial-see',
    updateDefaultModel: API_PREFIX + '/user/default-model/update',
    updateDefaultEngine: API_PREFIX + '/user/default-engine/update',
    updateDefaultReadMarkReason: API_PREFIX + '/user/read-mark-reason/update',
    updateDefaultFileSystem: API_PREFIX + '/user/default-file-system/update',
    createUserByGoogle: API_PREFIX + '/user/create/google',
    createUserByGithub: API_PREFIX + '/user/create/github',
    bindGitHub: API_PREFIX + '/user/bind/github',
    bindGoogle: API_PREFIX + '/user/bind/google',
    unBindGitHub: API_PREFIX + '/user/unbind/github',
    unBindGoogle: API_PREFIX + '/user/unbind/google',
    createSMSCode: API_PREFIX + '/user/create/sms/code',
    createSMSUserVerify: API_PREFIX + '/user/create/sms/verify',
    bindPhoneCode: API_PREFIX + '/user/bind/phone/code',
    bindPhoneVerify: API_PREFIX + '/user/bind/phone/verify',
    unBindPhone: API_PREFIX + '/user/unbind/phone',
    createUserByWechatWeb: API_PREFIX + '/user/create/wechat/web',
    createUserByWechatMini: API_PREFIX + '/user/create/wechat/mini',
    bindWeChat: API_PREFIX + '/user/bind/wechat/web',
    unBindWeChat: API_PREFIX + '/user/unbind/wechat',
} 