export const API_PREFIX = process.env.NEXT_PUBLIC_API_PREFIX
export const FILE_API_PREFIX = process.env.NEXT_PUBLIC_FILE_API_PREFIX
export const NOTIFICATION_WS_API_PREFIX = process.env.NEXT_PUBLIC_NOTIFICATION_WS_API_PREFIX