export const API_PREFIX = process.env.NEXT_PUBLIC_API_PREFIX
export const NOTIFICATION_WS_API_PREFIX = process.env.NEXT_PUBLIC_NOTIFICATION_WS_API_PREFIX
export const DAILY_HOT_API_PREFIX = process.env.NEXT_PUBLIC_HOT_NEWS_API_PREFIX
export const UNION_PAY_API_PREFIX = process.env.UNION_PAY_API_PREFIX