from __future__ import annotations

from datetime import datetime
from typing import Optional

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column

from data.sql.base import Base


class EmailUser(Base):
    __tablename__ = 'email_user'

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("user.id"), index=True, nullable=False)
    nickname: Mapped[Optional[str]] = mapped_column(String(200))
    email: Mapped[str] = mapped_column(String(100), index=True, nullable=False)
    hashed_password: Mapped[str] = mapped_column(String(255), nullable=False)
    delete_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    is_initial_password: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False, comment='Whether it is the initial password generated by the system')
    # 下列字段仅在用户在自己账号详情页绑定邮箱的时候会产生
    initial_password: Mapped[Optional[str]] = mapped_column(String(255), comment='The initial password generated by the system')
    has_seen_initial_password: Mapped[Optional[bool]] = mapped_column(Boolean, comment='Whether the initial password has been viewed')


class User(Base):
    __tablename__ = "user"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    uuid: Mapped[str] = mapped_column(String(100), index=True, nullable=False)
    avatar: Mapped[str] = mapped_column(String(500), nullable=False)
    nickname: Mapped[str] = mapped_column(String(50), index=True, nullable=False)
    last_login_ip: Mapped[Optional[str]] = mapped_column(String(50))
    last_login_time: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    slogan: Mapped[Optional[str]] = mapped_column(String(200))
    gender: Mapped[Optional[int]] = mapped_column(Integer, comment='0: unk, 1: male, 2: female')
    age: Mapped[Optional[int]] = mapped_column(Integer)
    is_forbidden: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    default_document_reader_model_id: Mapped[Optional[int]] = mapped_column(Integer)
    default_revornix_model_id: Mapped[Optional[int]] = mapped_column(Integer)
    default_file_document_parse_user_engine_id: Mapped[Optional[int]] = mapped_column(Integer)
    default_website_document_parse_user_engine_id: Mapped[Optional[int]] = mapped_column(Integer)
    default_podcast_user_engine_id: Mapped[Optional[int]] = mapped_column(Integer)
    default_image_generate_engine_id: Mapped[Optional[int]] = mapped_column(Integer)
    default_read_mark_reason: Mapped[Optional[int]] = mapped_column(Integer, comment='0: Request once, 1: Scroll to the bottom of the document, 2: Manually Mark')
    default_user_file_system: Mapped[Optional[int]] = mapped_column(Integer)
    create_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    update_time: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
    delete_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
