from enum import Enum

class Ability(Enum):
    COLLECT_FILE_LIMITED = "collect-file-limited"
    COLLECT_LINK_LIMITED = "collect-link-limited"
    COLLECT_FILE = "collect-file"
    COLLECT_LINK = "collect-link"
    COLLECT_QUICKNOTE = "collect-quicknote"
    RSS_ADD = "rss-add"
    RSS_DELETE = "rss-delete"
    RSS_UPDATE = "rss-update"
    API_COLLECT_LIMITED = "api-collect-limited"
    API_COLLECT_LIMITED_MORE = "api-collect-limited-more"
    API_COLLECT_LIMITED_MUCH_MORE = "api-collect-limited-much-more"
    SECTION_COLLABORATION = "section-collaboration"
    OFFICIAL_PROXIED_LLM_LIMITED = "official-proxied-llm-limited"
    OFFICIAL_PROXIED_PODCAST_GENERATOR_LIMITED = "official-proxied-podcast-generator-limited"
    OFFICIAL_PROXIED_IMAGE_GENERATOR_LIMITED = "official-proxied-image-generator-limited"
    OFFICIAL_PROXIED_LLM_LIMITED_MORE = "official-proxied-llm-limited-more"
    OFFICIAL_PROXIED_PODCAST_GENERATOR_LIMITED_MORE = "official-proxied-podcast-generator-limited-more"
    OFFICIAL_PROXIED_IMAGE_GENERATOR_LIMITED_MORE = "official-proxied-image-generator-limited-more"
    OFFICIAL_PROXIED_LLM_LIMITED_NONE = "official-proxied-llm-limited-none"
    OFFICIAL_PROXIED_PODCAST_GENERATOR_LIMITED_NONE = "official-proxied-podcast-generator-limited-none"
    OFFICIAL_PROXIED_IMAGE_GENERATOR_LIMITED_NONE = "official-proxied-image-generator-limited-none"
    MCP_CLIENT = "mcp-client"
    MCP_SERVER = "mcp-server"
    KNOWLEDGE_GRAPH = "knowledge-graph"