/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BonusWithdrawRequestDTO,
  NormalResponseDTO,
} from '../models/index';
import {
    BonusWithdrawRequestDTOFromJSON,
    BonusWithdrawRequestDTOToJSON,
    NormalResponseDTOFromJSON,
    NormalResponseDTOToJSON,
} from '../models/index';

export interface WithdrawBonusRequest {
    bonusWithdrawRequestDTO: BonusWithdrawRequestDTO;
}

/**
 * 
 */
export class BonusControllerApi extends runtime.BaseAPI {

    /**
     */
    async withdrawBonusRaw(requestParameters: WithdrawBonusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NormalResponseDTO>> {
        if (requestParameters['bonusWithdrawRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'bonusWithdrawRequestDTO',
                'Required parameter "bonusWithdrawRequestDTO" was null or undefined when calling withdrawBonus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/bonus/withdraw`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BonusWithdrawRequestDTOToJSON(requestParameters['bonusWithdrawRequestDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NormalResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async withdrawBonus(requestParameters: WithdrawBonusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NormalResponseDTO> {
        const response = await this.withdrawBonusRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
