/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetOrderDetailByPaypalOrderRequestDTO,
  GetOrderDetailRequestDTO,
  GetOrderDetailResponseDTO,
  OrderStatusRequestDTO,
  OrderStatusResponseDTO,
} from '../models/index';
import {
    GetOrderDetailByPaypalOrderRequestDTOFromJSON,
    GetOrderDetailByPaypalOrderRequestDTOToJSON,
    GetOrderDetailRequestDTOFromJSON,
    GetOrderDetailRequestDTOToJSON,
    GetOrderDetailResponseDTOFromJSON,
    GetOrderDetailResponseDTOToJSON,
    OrderStatusRequestDTOFromJSON,
    OrderStatusRequestDTOToJSON,
    OrderStatusResponseDTOFromJSON,
    OrderStatusResponseDTOToJSON,
} from '../models/index';

export interface GetOrderDetailRequest {
    getOrderDetailRequestDTO: GetOrderDetailRequestDTO;
}

export interface GetOrderDetailByPaypalOrderRequest {
    getOrderDetailByPaypalOrderRequestDTO: GetOrderDetailByPaypalOrderRequestDTO;
}

export interface GetOrderStatusRequest {
    orderStatusRequestDTO: OrderStatusRequestDTO;
}

export interface PaypalCallbackRequest {
    body: string;
}

/**
 * 
 */
export class OrderControllerApi extends runtime.BaseAPI {

    /**
     */
    async getOrderDetailRaw(requestParameters: GetOrderDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetOrderDetailResponseDTO>> {
        if (requestParameters['getOrderDetailRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'getOrderDetailRequestDTO',
                'Required parameter "getOrderDetailRequestDTO" was null or undefined when calling getOrderDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/order/detail`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetOrderDetailRequestDTOToJSON(requestParameters['getOrderDetailRequestDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetOrderDetailResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async getOrderDetail(requestParameters: GetOrderDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetOrderDetailResponseDTO> {
        const response = await this.getOrderDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getOrderDetailByPaypalOrderRaw(requestParameters: GetOrderDetailByPaypalOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetOrderDetailResponseDTO>> {
        if (requestParameters['getOrderDetailByPaypalOrderRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'getOrderDetailByPaypalOrderRequestDTO',
                'Required parameter "getOrderDetailByPaypalOrderRequestDTO" was null or undefined when calling getOrderDetailByPaypalOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/order/detail/paypal`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetOrderDetailByPaypalOrderRequestDTOToJSON(requestParameters['getOrderDetailByPaypalOrderRequestDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetOrderDetailResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async getOrderDetailByPaypalOrder(requestParameters: GetOrderDetailByPaypalOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetOrderDetailResponseDTO> {
        const response = await this.getOrderDetailByPaypalOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getOrderStatusRaw(requestParameters: GetOrderStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderStatusResponseDTO>> {
        if (requestParameters['orderStatusRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'orderStatusRequestDTO',
                'Required parameter "orderStatusRequestDTO" was null or undefined when calling getOrderStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/order/status`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OrderStatusRequestDTOToJSON(requestParameters['orderStatusRequestDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderStatusResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async getOrderStatus(requestParameters: GetOrderStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderStatusResponseDTO> {
        const response = await this.getOrderStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async paypalCallbackRaw(requestParameters: PaypalCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling paypalCallback().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/order/callback/paypal`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async paypalCallback(requestParameters: PaypalCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.paypalCallbackRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
