/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetOrderDetailRequestDTO,
  GetOrderDetailResponseDTO,
  OrderStatusRequestDTO,
  OrderStatusResponseDTO,
} from '../models/index';
import {
    GetOrderDetailRequestDTOFromJSON,
    GetOrderDetailRequestDTOToJSON,
    GetOrderDetailResponseDTOFromJSON,
    GetOrderDetailResponseDTOToJSON,
    OrderStatusRequestDTOFromJSON,
    OrderStatusRequestDTOToJSON,
    OrderStatusResponseDTOFromJSON,
    OrderStatusResponseDTOToJSON,
} from '../models/index';

export interface GetOrderDetailRequest {
    getOrderDetailRequestDTO: GetOrderDetailRequestDTO;
}

export interface GetOrderStatusRequest {
    orderStatusRequestDTO: OrderStatusRequestDTO;
}

/**
 * 
 */
export class OrderControllerApi extends runtime.BaseAPI {

    /**
     */
    async alipayCallbackRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/order/callback/alipay`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async alipayCallback(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.alipayCallbackRaw(initOverrides);
    }

    /**
     */
    async getOrderDetailRaw(requestParameters: GetOrderDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetOrderDetailResponseDTO>> {
        if (requestParameters['getOrderDetailRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'getOrderDetailRequestDTO',
                'Required parameter "getOrderDetailRequestDTO" was null or undefined when calling getOrderDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/order/detail`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetOrderDetailRequestDTOToJSON(requestParameters['getOrderDetailRequestDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetOrderDetailResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async getOrderDetail(requestParameters: GetOrderDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetOrderDetailResponseDTO> {
        const response = await this.getOrderDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getOrderStatusRaw(requestParameters: GetOrderStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderStatusResponseDTO>> {
        if (requestParameters['orderStatusRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'orderStatusRequestDTO',
                'Required parameter "orderStatusRequestDTO" was null or undefined when calling getOrderStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/order/status`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OrderStatusRequestDTOToJSON(requestParameters['orderStatusRequestDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderStatusResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async getOrderStatus(requestParameters: GetOrderStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderStatusResponseDTO> {
        const response = await this.getOrderStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async weChatCallbackRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/order/callback/wechat`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async weChatCallback(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.weChatCallbackRaw(initOverrides);
    }

}
