/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetProductAbilitiesRequestDTO,
  GetProductAbilitiesResponseDTO,
  GetProductRequestByUUIDDTO,
  GetProductResponseDTO,
  PrePayProductRequestDTO,
  PrePayProductResponseDTO,
} from '../models/index';
import {
    GetProductAbilitiesRequestDTOFromJSON,
    GetProductAbilitiesRequestDTOToJSON,
    GetProductAbilitiesResponseDTOFromJSON,
    GetProductAbilitiesResponseDTOToJSON,
    GetProductRequestByUUIDDTOFromJSON,
    GetProductRequestByUUIDDTOToJSON,
    GetProductResponseDTOFromJSON,
    GetProductResponseDTOToJSON,
    PrePayProductRequestDTOFromJSON,
    PrePayProductRequestDTOToJSON,
    PrePayProductResponseDTOFromJSON,
    PrePayProductResponseDTOToJSON,
} from '../models/index';

export interface GetProductByIdRequest {
    getProductRequestByUUIDDTO: GetProductRequestByUUIDDTO;
}

export interface ListProductAbilityRequest {
    getProductAbilitiesRequestDTO: GetProductAbilitiesRequestDTO;
}

export interface PrePayProductRequest {
    prePayProductRequestDTO: PrePayProductRequestDTO;
}

/**
 * 
 */
export class ProductControllerApi extends runtime.BaseAPI {

    /**
     */
    async getProductByIdRaw(requestParameters: GetProductByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetProductResponseDTO>> {
        if (requestParameters['getProductRequestByUUIDDTO'] == null) {
            throw new runtime.RequiredError(
                'getProductRequestByUUIDDTO',
                'Required parameter "getProductRequestByUUIDDTO" was null or undefined when calling getProductById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/product/detail`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetProductRequestByUUIDDTOToJSON(requestParameters['getProductRequestByUUIDDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetProductResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async getProductById(requestParameters: GetProductByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetProductResponseDTO> {
        const response = await this.getProductByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listProductAbilityRaw(requestParameters: ListProductAbilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetProductAbilitiesResponseDTO>> {
        if (requestParameters['getProductAbilitiesRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'getProductAbilitiesRequestDTO',
                'Required parameter "getProductAbilitiesRequestDTO" was null or undefined when calling listProductAbility().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/product/ability/list`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetProductAbilitiesRequestDTOToJSON(requestParameters['getProductAbilitiesRequestDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetProductAbilitiesResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async listProductAbility(requestParameters: ListProductAbilityRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetProductAbilitiesResponseDTO> {
        const response = await this.listProductAbilityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async prePayProductRaw(requestParameters: PrePayProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PrePayProductResponseDTO>> {
        if (requestParameters['prePayProductRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'prePayProductRequestDTO',
                'Required parameter "prePayProductRequestDTO" was null or undefined when calling prePayProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/product/prepay`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PrePayProductRequestDTOToJSON(requestParameters['prePayProductRequestDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PrePayProductResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async prePayProduct(requestParameters: PrePayProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PrePayProductResponseDTO> {
        const response = await this.prePayProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
