/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConfirmAppleSubscriptionRequestDTO,
  ConfirmSubscriptionResponseDTO,
  PrePaySubscriptionRequestDTO,
  PrePaySubscriptionResponseDTO,
  SubscriptionStatusRequestDTO,
  SubscriptionStatusResponseDTO,
} from '../models/index';
import {
    ConfirmAppleSubscriptionRequestDTOFromJSON,
    ConfirmAppleSubscriptionRequestDTOToJSON,
    ConfirmSubscriptionResponseDTOFromJSON,
    ConfirmSubscriptionResponseDTOToJSON,
    PrePaySubscriptionRequestDTOFromJSON,
    PrePaySubscriptionRequestDTOToJSON,
    PrePaySubscriptionResponseDTOFromJSON,
    PrePaySubscriptionResponseDTOToJSON,
    SubscriptionStatusRequestDTOFromJSON,
    SubscriptionStatusRequestDTOToJSON,
    SubscriptionStatusResponseDTOFromJSON,
    SubscriptionStatusResponseDTOToJSON,
} from '../models/index';

export interface AppleCallbackRequest {
    body: string;
}

export interface ConfirmAppleSubscriptionRequest {
    confirmAppleSubscriptionRequestDTO: ConfirmAppleSubscriptionRequestDTO;
}

export interface GetSubscriptionStatusRequest {
    subscriptionStatusRequestDTO: SubscriptionStatusRequestDTO;
}

export interface PrePaySubscriptionRequest {
    prePaySubscriptionRequestDTO: PrePaySubscriptionRequestDTO;
}

/**
 * 
 */
export class SubscriptionControllerApi extends runtime.BaseAPI {

    /**
     */
    async appleCallbackRaw(requestParameters: AppleCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling appleCallback().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/subscription/callback/apple`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async appleCallback(requestParameters: AppleCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.appleCallbackRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async confirmAppleSubscriptionRaw(requestParameters: ConfirmAppleSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfirmSubscriptionResponseDTO>> {
        if (requestParameters['confirmAppleSubscriptionRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'confirmAppleSubscriptionRequestDTO',
                'Required parameter "confirmAppleSubscriptionRequestDTO" was null or undefined when calling confirmAppleSubscription().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/subscription/apple/confirm`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfirmAppleSubscriptionRequestDTOToJSON(requestParameters['confirmAppleSubscriptionRequestDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfirmSubscriptionResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async confirmAppleSubscription(requestParameters: ConfirmAppleSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfirmSubscriptionResponseDTO> {
        const response = await this.confirmAppleSubscriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getSubscriptionStatusRaw(requestParameters: GetSubscriptionStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionStatusResponseDTO>> {
        if (requestParameters['subscriptionStatusRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'subscriptionStatusRequestDTO',
                'Required parameter "subscriptionStatusRequestDTO" was null or undefined when calling getSubscriptionStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/subscription/status`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubscriptionStatusRequestDTOToJSON(requestParameters['subscriptionStatusRequestDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionStatusResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async getSubscriptionStatus(requestParameters: GetSubscriptionStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionStatusResponseDTO> {
        const response = await this.getSubscriptionStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async prePaySubscriptionRaw(requestParameters: PrePaySubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PrePaySubscriptionResponseDTO>> {
        if (requestParameters['prePaySubscriptionRequestDTO'] == null) {
            throw new runtime.RequiredError(
                'prePaySubscriptionRequestDTO',
                'Required parameter "prePaySubscriptionRequestDTO" was null or undefined when calling prePaySubscription().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/subscription/prepay`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PrePaySubscriptionRequestDTOToJSON(requestParameters['prePaySubscriptionRequestDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PrePaySubscriptionResponseDTOFromJSON(jsonValue));
    }

    /**
     */
    async prePaySubscription(requestParameters: PrePaySubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PrePaySubscriptionResponseDTO> {
        const response = await this.prePaySubscriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
