import os

FILE_SYSTEM_USER_NAME = os.environ.get('FILE_SYSTEM_USER_NAME')
FILE_SYSTEM_PASSWORD = os.environ.get('FILE_SYSTEM_PASSWORD')
FILE_SYSTEM_SERVER_PUBLIC_URL = os.environ.get('FILE_SYSTEM_SERVER_PUBLIC_URL')