from __future__ import annotations

from datetime import datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column

from data.sql.base import Base


class WechatUser(Base):
    __tablename__ = 'wechat_user'

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("user.id"), index=True, nullable=False)
    wechat_user_union_id: Mapped[str] = mapped_column(String(100), index=True, nullable=False)
    wechat_user_open_id: Mapped[str] = mapped_column(String(100), index=True, nullable=False)
    wechat_user_name: Mapped[str | None] = mapped_column(String(100))
    wechat_platform: Mapped[int] = mapped_column(Integer, nullable=False, comment='0: unknown, 1: Revornix WeChat Web App, 2: Revornix WeChat Mini Program')
    delete_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class PhoneUser(Base):
    __tablename__ = 'phone_user'

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("user.id"), index=True, nullable=False)
    phone: Mapped[str] = mapped_column(String(20), index=True, nullable=False)
    delete_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class GoogleUser(Base):
    __tablename__ = 'google_user'

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("user.id"), index=True, nullable=False)
    google_user_id: Mapped[str] = mapped_column(String(100), index=True, nullable=False)
    google_user_name: Mapped[str | None] = mapped_column(String(100))
    delete_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class GithubUser(Base):
    __tablename__ = 'github_user'

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("user.id"), index=True, nullable=False)
    github_user_id: Mapped[str] = mapped_column(String(100), index=True, nullable=False)
    github_user_name: Mapped[str | None] = mapped_column(String(100))
    delete_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class EmailUser(Base):
    __tablename__ = 'email_user'

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("user.id"), index=True, nullable=False)
    nickname: Mapped[str | None] = mapped_column(String(200))
    email: Mapped[str] = mapped_column(String(100), index=True, nullable=False)
    hashed_password: Mapped[str] = mapped_column(String(255), nullable=False)
    delete_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    is_initial_password: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False, comment='Whether it is the initial password generated by the system')
    # 下列字段仅在用户在自己账号详情页绑定邮箱的时候会产生
    initial_password: Mapped[str | None] = mapped_column(String(255), comment='The initial password generated by the system')
    has_seen_initial_password: Mapped[bool | None] = mapped_column(Boolean, comment='Whether the initial password has been viewed')


class FollowUser(Base):
    __tablename__ = "follow_user"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    to_user_id: Mapped[int] = mapped_column(ForeignKey("user.id"), index=True, nullable=False)
    from_user_id: Mapped[int] = mapped_column(ForeignKey("user.id"), index=True, nullable=False)
    create_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    update_time: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    delete_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class User(Base):
    __tablename__ = "user"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    uuid: Mapped[str] = mapped_column(String(100), index=True, nullable=False)
    role: Mapped[int] = mapped_column(Integer, nullable=False, comment='1: root, 2: admin, 3: user')
    avatar: Mapped[str] = mapped_column(String(500), nullable=False)
    nickname: Mapped[str] = mapped_column(String(50), index=True, nullable=False)
    last_login_ip: Mapped[str | None] = mapped_column(String(50))
    last_login_time: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    slogan: Mapped[str | None] = mapped_column(String(200))
    gender: Mapped[int | None] = mapped_column(Integer, comment='0: unk, 1: male, 2: female')
    age: Mapped[int | None] = mapped_column(Integer)
    is_forbidden: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    default_document_reader_model_id: Mapped[int | None] = mapped_column(Integer)
    default_revornix_model_id: Mapped[int | None] = mapped_column(Integer)
    default_file_document_parse_user_engine_id: Mapped[int | None] = mapped_column(Integer)
    default_website_document_parse_user_engine_id: Mapped[int | None] = mapped_column(Integer)
    default_podcast_user_engine_id: Mapped[int | None] = mapped_column(Integer)
    default_audio_transcribe_engine_id: Mapped[int | None] = mapped_column(Integer)
    default_image_generate_engine_id: Mapped[int | None] = mapped_column(Integer)
    default_read_mark_reason: Mapped[int | None] = mapped_column(Integer, comment='0: Request once, 1: Scroll to the bottom of the document, 2: Manually Mark')
    default_user_file_system: Mapped[int | None] = mapped_column(Integer)
    create_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    update_time: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    delete_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
