import os

MYSQL_USER_NAME = os.environ.get('MYSQL_USER_NAME')
MYSQL_PASSWORD = os.environ.get('MYSQL_PASSWORD')
MYSQL_DATABASE_URL = os.environ.get('MYSQL_DATABASE_URL')
MYSQL_DATABASE_NAME = os.environ.get('MYSQL_DATABASE_NAME')